apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: example-secure
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      volumes:
      - name: client-certs
        emptyDir: {}

      initContainers:
      # The init-certs container sends a certificate signing request to the
      # kubernetes cluster.
      # You can see pending requests using: kubectl get csr
      # CSRs can be approved using:         kubectl certificate approve <csr name>
      #
      # In addition to the client certificate and key, the init-certs entrypoint will symlink
      # the cluster CA to the certs directory.
      - name: init-certs
        image: cockroachdb/cockroach-k8s-request-cert:0.1
        imagePullPolicy: IfNotPresent
        args:
        - "-certs-dir=/cockroach-certs"
        - "-type=client"
        - "-user=root"
        - "-symlink-ca-from=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        volumeMounts:
        - name: client-certs
          mountPath: /cockroach-certs

      containers:
      - name: loadgen
        image: cockroachdb/loadgen-kv:0.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: client-certs
          mountPath: /cockroach-certs
        command:
          - "/kv"
          - "postgres://root@cockroachdb-public:26257/kv?sslmode=verify-full&sslcert=/cockroach-certs/client.root.crt&sslkey=/cockroach-certs/client.root.key&sslrootcert=/cockroach-certs/ca.crt"
